/* Charlotte — revision bank seed (practice engine).
   Each entry is one problem. variant 0 = the original miss from her test; 1, 2, ... = your variations.
   Fields: id (unique forever), topic, variant, type (qc | mc | ma | ne), stem, qa/qb (qc only),
           choices (mc/ma), answer (index, array of indices, or string for ne), given (what she put on the test),
           source, explain, trap, figure (optional inline SVG), frac:true (ne with a fraction box).
   Add new problems at the END. Never reuse or edit an id once it has shipped. */
var FIG_ANGLES = '<svg class="fig" width="300" height="270" viewBox="0 0 340 300" fill="none" stroke="#222" stroke-width="1.7" stroke-linecap="round" font-family="Times New Roman" font-style="italic" font-size="16">'
 +'<line x1="80" y1="41" x2="268" y2="270"/><line x1="170" y1="15" x2="170" y2="290"/><line x1="238" y1="30" x2="102" y2="270"/><line x1="170" y1="150" x2="335" y2="210"/>'
 +'<text x="66" y="34" stroke="none" fill="#222" font-size="18">k</text><text x="164" y="10" stroke="none" fill="#222" font-size="18">&#8467;</text><text x="244" y="26" stroke="none" fill="#222" font-size="18">m</text>'
 +'<text x="139" y="104" stroke="none" fill="#222">w&deg;</text><text x="178" y="101" stroke="none" fill="#222">x&deg;</text><text x="196" y="140" stroke="none" fill="#222">y&deg;</text>'
 +'<text x="214" y="196" stroke="none" fill="#222">z&deg;</text><text x="128" y="168" stroke="none" fill="#222">v&deg;</text></svg>';

window.RBANK_SEED = [
 /* ---- Topic 1: QC with ranges / extremes ---- */
 { id:'qc-extremes-0', topic:'QC: extremes of a range', variant:0, type:'qc',
   stem:'', qa:'The greatest possible value of $\\dfrac{2}{x-y}$, where $6 \\le x \\le 8$ and $2 \\le y \\le 5$', qb:'$\\dfrac{2}{3}$',
   answer:0, given:3, source:'Practice test, Q1',
   explain:'$x-y$ runs from $6-5=1$ up to $8-2=6$, and it is always positive. A fraction with a fixed positive numerator is biggest when the denominator is smallest, so the greatest value is $\\dfrac{2}{1}=2$, which beats $\\dfrac{2}{3}$.',
   trap:'&ldquo;Cannot be determined&rdquo; is tempting because $x$ and $y$ are ranges, not numbers. But the question asks for the <em>greatest possible value</em> &mdash; that is a single number, found by pushing the denominator to its extreme. Ranges in a QC stem are a cue to test endpoints, not to bail out.' },
 { id:'qc-extremes-1', topic:'QC: extremes of a range', variant:1, type:'qc',
   stem:'', qa:'The least possible value of $\\dfrac{3}{a-b}$, where $10 \\le a \\le 12$ and $1 \\le b \\le 4$', qb:'$\\dfrac{1}{3}$',
   answer:1,
   explain:'$a-b$ ranges from $6$ to $11$ (always positive). The fraction is smallest when the denominator is largest: $\\dfrac{3}{11}\\approx 0.27 < \\dfrac{1}{3}\\approx 0.33$. Quantity B is greater.',
   trap:'Same trap as the original: ranges invite choice D. Test both endpoints of the denominator before deciding anything.' },

 /* ---- Topic 2: Recursive sequences & exponents ---- */
 { id:'seq-exp-0', topic:'Sequences & exponent rules', variant:0, type:'qc',
   stem:'$C_1, C_2, C_3, \\ldots, C_j, \\ldots$<br>The sequence shown is defined by $C_1 = 5$ and $C_{j+1} = \\dfrac{1}{5}C_j$ for each positive integer $j$.',
   qa:'$C_{10}$', qb:'$\\left(5^{15}\\right)C_{25}$', answer:2, given:1, source:'Practice test, Q2',
   explain:'Each step multiplies by $\\frac15$, so $C_n = 5\\cdot\\left(\\frac15\\right)^{n-1} = 5^{2-n}$. Then $C_{10}=5^{-8}$ and $5^{15}C_{25} = 5^{15}\\cdot 5^{-23} = 5^{-8}$. Equal.',
   trap:'B looks bigger because $5^{15}$ is huge and $25 > 10$. But $C_{25}$ is <em>tiny</em> ($5^{-23}$), and the $5^{15}$ only partly cancels it. Write the closed form $C_n=5^{2-n}$ first; never compare by eyeballing which subscript is larger.' },
 { id:'seq-exp-1', topic:'Sequences & exponent rules', variant:1, type:'qc',
   stem:'The sequence $a_1, a_2, a_3, \\ldots$ is defined by $a_1 = 3$ and $a_{n+1} = 3a_n$ for each positive integer $n$.',
   qa:'$a_8$', qb:'$3^8$', answer:2,
   explain:'$a_n = 3\\cdot 3^{n-1} = 3^n$, so $a_8 = 3^8$. Equal.',
   trap:'Easy to think $a_8 = 3\\cdot 3^8$ (one factor too many) or $3^7$ (one too few). Check with $n=1$: the formula must give $a_1=3$.' },

 /* ---- Topic 3: Simple interest / two-account setup ---- */
 { id:'interest-0', topic:'Simple interest, two accounts', variant:0, type:'mc',
   stem:'An investor placed a total of \\$6,400 in two accounts for one year. One of the accounts earned simple annual interest at a rate of 5 percent, and the other earned simple annual interest at a rate of 3 percent. The investor made no deposits or withdrawals from the accounts. If each account earned the same amount of interest after one year, what was the total amount of interest earned from both accounts?',
   choices:['\\$128','\\$144','\\$240','\\$256','\\$512'], answer:2, given:0, source:'Practice test, Q3',
   explain:'Let the 5% account hold $a$ and the 3% account hold $b$. Equal interest means $0.05a = 0.03b$, so $a:b = 3:5$. Split \\$6,400 in that ratio: $a=2{,}400$, $b=4{,}000$. Each earns \\$120, total \\$240.',
   trap:'\\$128 is what you get from $6400 \\times 0.04 \\div 2$ &mdash; averaging the two rates. Averaging only works when the accounts hold equal money, and here they can&rsquo;t (equal interest at different rates forces unequal balances).' },
 { id:'interest-1', topic:'Simple interest, two accounts', variant:1, type:'mc',
   stem:'A total of \\$10,000 was placed in two accounts for one year. One account earned simple annual interest at 6 percent and the other at 4 percent. If each account earned the same amount of interest after one year, what was the total interest earned from both accounts?',
   choices:['\\$400','\\$480','\\$500','\\$600','\\$960'], answer:1,
   explain:'$0.06a = 0.04b \\Rightarrow a:b = 2:3$, so $a=4{,}000$, $b=6{,}000$. Each earns \\$240; total \\$480.',
   trap:'\\$500 is the average-rate trap ($10{,}000\\times 5\\%$). Equal interest at different rates means unequal balances &mdash; set up the ratio.' },

 /* ---- Topic 4: Angles at a point ---- */
 { id:'angles-0', topic:'Angles at a point', variant:0, type:'ne', frac:true, figure:FIG_ANGLES,
   stem:'In the figure, lines $k$, $\\ell$, and $m$ intersect at a single point, which is the vertex of all the angles shown. If $x = z$, $y = 2w$, and $v = 110$, what is the ratio of $x$ to $w$?<br><span style="font-size:16px">Give your answer as a fraction.</span>',
   answer:'3/4', given:'2/3', source:'Practice test, Q4',
   explain:'Look at the figure before the equations. The region straight across the vertex from $v$ is bounded by the same two lines, and it contains <em>both</em> $y$ and $z$ (the extra ray splits it). Vertical angles are equal, so $y + z = v = 110$. Along line $k$, the four angles on one side make a straight line: $w + x + y + z = 180$, so $w + x = 70$. Now substitute $y = 2w$ and $z = x$ into the first equation: $2w + x = 110$. Subtract $w + x = 70$ to get $w = 40$, then $x = 30$. Ratio $x:w = 30:40 = \\dfrac{3}{4}$.',
   trap:'$\\frac23$ comes from treating $v$ as vertical to $y$ alone and never noticing the extra ray. In a busy figure, trace each labeled region straight through the vertex with your finger first: the partner of $v$ is $y$ and $z$ together. Get the two geometry facts (vertical pair, straight line) down, then the algebra is two lines.' },
 { id:'angles-1', topic:'Angles at a point', variant:1, type:'ne',
   stem:'Three lines intersect at a single point, forming six angles. Three consecutive angles, measuring $p°$, $q°$, and $r°$, together make up a straight line. If $p = q$ and $r = 4p$, what is the value of $r$?',
   answer:'120',
   explain:'$p+q+r = 180$ and $q=p$, $r=4p$, so $6p = 180$, $p = 30$, $r = 120$.',
   trap:'Forgetting that consecutive angles along a line sum to $180°$ (not $360°$) doubles everything.' },

 /* ---- Topic 5: Area unit conversion ---- */
 { id:'units-0', topic:'Unit conversion for area', variant:0, type:'ma',
   stem:'A flat rectangular tile has a length that is between 4 inches and 6 inches and a width that is between 3 inches and 6 inches. Which of the following could be the value of the area, in square feet, of the top surface of the tile? (1 foot = 12 inches)<br><span style="font-size:16px">Indicate <u>all</u> such values.</span>',
   choices:['$\\dfrac{1}{8}$','$\\dfrac{1}{6}$','$\\dfrac{1}{2}$','$\\dfrac{4}{3}$'], answer:[0,1], given:[3], source:'Practice test, Q5',
   explain:'Area in square inches is between $4\\cdot 3 = 12$ and $6\\cdot 6 = 36$. One square foot is $12\\times 12 = 144$ square inches, so the area in square feet is between $\\dfrac{12}{144}=\\dfrac{1}{12}$ and $\\dfrac{36}{144}=\\dfrac{1}{4}$. Only $\\dfrac18$ and $\\dfrac16$ fit.',
   trap:'$\\frac43$ is exactly what you get by dividing by 12 instead of 144 (12&ndash;36 in&sup2; becomes 1&ndash;3 &ldquo;ft&sup2;&rdquo;). Converting <em>area</em> means the conversion factor gets squared. Convert the side lengths to feet first, then multiply.' },
 { id:'units-1', topic:'Unit conversion for area', variant:1, type:'ma',
   stem:'A rectangular rug has a length between 5 feet and 8 feet and a width between 3 feet and 4 feet. Which of the following could be the area of the rug, in square yards? (1 yard = 3 feet)<br><span style="font-size:16px">Indicate <u>all</u> such values.</span>',
   choices:['$1$','$2$','$3$','$4$','$10$'], answer:[1,2],
   explain:'Area in ft&sup2; is between $15$ and $32$. One square yard is $9$ ft&sup2;, so the area in yd&sup2; is between $\\frac{15}{9}\\approx 1.67$ and $\\frac{32}{9}\\approx 3.56$. Only $2$ and $3$ fit.',
   trap:'Dividing by 3 instead of 9 gives 5&ndash;10.7, which makes $10$ look right. Square the conversion factor for area.' },

 /* ---- Topic 6: Digit arrangement / min difference ---- */
 { id:'digits-0', topic:'Digits & least difference', variant:0, type:'mc',
   stem:'If 2, 4, 6, and 9 are the digits of two 2-digit integers, what is the least possible positive difference between the integers?',
   choices:['28','27','17','13','9'], answer:3, given:2, source:'Practice test, Q6',
   explain:'To make the difference small, give the two numbers tens digits that are as close as possible (consecutive in the list), then make the larger number&rsquo;s units digit small and the smaller number&rsquo;s units digit large. Tens 4 and 6: $62 - 49 = 13$. Tens 2 and 4: $42 - 29 = 13$. Tens 6 and 9: $92-69=23$. Least is $13$.',
   trap:'17 comes from a &ldquo;reasonable-looking&rdquo; pair like $46 - 29$ without pushing the units digits to their extremes. Once the tens digits are chosen, you still have a second optimization: largest units on the small number, smallest units on the big number.' },
 { id:'digits-1', topic:'Digits & least difference', variant:1, type:'mc',
   stem:'If 1, 4, 5, and 7 are the digits of two 2-digit integers, what is the least possible positive difference between the integers?',
   choices:['4','6','13','14','27'], answer:0,
   explain:'Tens digits 4 and 5 are closest: $51 - 47 = 4$. (Tens 1 and 4: $41-17=24$; tens 5 and 7: $71-54=17$.) Least is $4$.',
   trap:'Stopping at $54-41=13$ uses consecutive tens but the wrong units placement. Always finish the second step.' },

 /* ---- Topic 7: Remainders ---- */
 { id:'remainder-0', topic:'Remainders', variant:0, type:'mc',
   stem:'When the positive integer $d$ is divided by 12, the remainder is 5. What is the remainder when $d^2$ is divided by 8?',
   choices:['1','3','5','6','7'], answer:0, given:1, source:'Practice test, Q7',
   explain:'Pick the simplest $d$ that works: $d = 5$. Then $d^2 = 25$ and $25 \\div 8$ leaves remainder $1$. (Check $d=17$: $289 = 36\\cdot 8 + 1$. Same.) Algebraically, $d = 12k+5 \\Rightarrow d^2 = 144k^2 + 120k + 25$, and the first two terms are multiples of 8, so the remainder is that of $25$, which is $1$.',
   trap:'The divisor changes from 12 to 8 mid-problem, which makes people freeze or guess. Remainder problems almost always surrender to <em>plug in the smallest valid number</em>. There was no reason to reason abstractly here.' },
 { id:'remainder-1', topic:'Remainders', variant:1, type:'mc',
   stem:'When the positive integer $n$ is divided by 10, the remainder is 7. What is the remainder when $n^2$ is divided by 5?',
   choices:['0','1','2','3','4'], answer:4,
   explain:'Try $n = 7$: $49 \\div 5$ leaves remainder $4$. (Check $n=17$: $289 = 57\\cdot5+4$.) Remainder $4$.',
   trap:'Changing divisors (10 &rarr; 5) is a cue to plug in, not to derive.' },

 /* ---- Topic 8: Algebraic fractions from a story ---- */
 { id:'algfrac-0', topic:'Algebraic fractions from a story', variant:0, type:'mc',
   stem:'A group of $n$ college students bought three identical round cakes to share. They divided the first cake into equal-sized pieces, one piece for each of them. They did the same with the second cake. After 3 of the students decided they did not want any more cake, the remaining students divided the third cake into equal-sized pieces, one piece for each of them. If Silvia received 1 piece from each of the three cakes, then, in terms of $n$, the amount of cake that she received was the same as what fraction of 1 cake?',
   choices:['$\\dfrac{n+2}{n(n-3)}$','$\\dfrac{2n-3}{n(n-3)}$','$\\dfrac{3n-3}{n(n-3)}$','$\\dfrac{3n-6}{n(n-3)}$','$\\dfrac{3n-3}{2n(n-3)}$'], answer:3, given:2, source:'Practice test, Q8',
   explain:'Silvia gets $\\frac1n + \\frac1n + \\frac{1}{n-3} = \\frac{2}{n} + \\frac{1}{n-3}$. Common denominator $n(n-3)$: $\\dfrac{2(n-3) + n}{n(n-3)} = \\dfrac{3n-6}{n(n-3)}$.',
   trap:'$3n-3$ is what you get if $2(n-3)$ becomes $2n-3$ &mdash; distributing the 2 to only the first term. The distractor is built from exactly that slip. Alternative safety net: plug in $n=6$. She gets $\\frac16+\\frac16+\\frac13 = \\frac23$; only choice D gives $\\frac{12}{18}=\\frac23$.' },
 { id:'algfrac-1', topic:'Algebraic fractions from a story', variant:1, type:'mc',
   stem:'$m$ friends bought three identical pizzas. They split the first pizza equally, one slice each, and did the same with the second. Then 2 friends left, and the remaining friends split the third pizza equally, one slice each. If Lena got one slice from each pizza, what fraction of 1 pizza did she receive, in terms of $m$?',
   choices:['$\\dfrac{3m-2}{m(m-2)}$','$\\dfrac{3m-4}{m(m-2)}$','$\\dfrac{m+2}{m(m-2)}$','$\\dfrac{2m-4}{m(m-2)}$','$\\dfrac{3m-4}{2m(m-2)}$'], answer:1,
   explain:'$\\frac2m + \\frac{1}{m-2} = \\dfrac{2(m-2)+m}{m(m-2)} = \\dfrac{3m-4}{m(m-2)}$.',
   trap:'$3m-2$ is the &ldquo;distribute to one term only&rdquo; slip again. Plug in $m=4$ to check: $\\frac14+\\frac14+\\frac12 = 1$; only B gives $\\frac{8}{8}$.' },

 /* ==== Added 2026-08-21 — PowerPrep Plus 2 misses ==== */
 {
  id: "qc-rational-0",
  topic: "QC: clearing a denominator safely",
  variant: 0,
  type: "qc",
  ts: 1787340000001,
  stem: "$x \\ne 1$",
  qa: "$\\dfrac{x^2-2}{x-1}$",
  qb: "$x+2$",
  answer: 3,
  given: 1,
  source: "PowerPrep Plus 2",
  explain: "Subtract instead of cross-multiplying: $\\dfrac{x^2-2}{x-1} - (x+2) = \\dfrac{x^2-2 - (x+2)(x-1)}{x-1} = \\dfrac{-x}{x-1}$. Now test signs: at $x=0$ this is $0$ (equal); at $x=3$ it is negative (B greater); at $x=\\tfrac12$ it is positive (A greater). All three happen, so the answer is D.",
  trap: "Multiplying both sides by $x-1$ feels natural, but $x-1$ can be negative, which flips the inequality &mdash; and testing only a couple of positive values (like $x=3$) makes B look safe. In a QC with a variable denominator, subtract and study the sign, and always try a value in every region: big, small, between, and the value that makes things equal." },
 {
  id: "qc-rational-1",
  topic: "QC: clearing a denominator safely",
  variant: 1,
  type: "qc",
  ts: 1787340000002,
  stem: "$x \\ne 2$",
  qa: "$\\dfrac{x^2-3}{x-2}$",
  qb: "$x+2$",
  answer: 3,
  explain: "$\\dfrac{x^2-3}{x-2}-(x+2) = \\dfrac{x^2-3-(x^2-4)}{x-2} = \\dfrac{1}{x-2}$. Positive when $x>2$ (A greater), negative when $x<2$ (B greater). D.",
  trap: "Same setup: the sign of the denominator decides everything, so one test value proves nothing." },
 {
  id: "sq-midpoints-0",
  topic: "Areas from midpoints in a square",
  variant: 0,
  type: "mc",
  ts: 1787340000003,
  figure: "<svg class=\"fig\" width=\"230\" height=\"230\" viewBox=\"0 0 230 230\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"14\"><polygon points=\"20,200 110,200 140,140 80,80\" fill=\"#cfcfcf\" stroke=\"none\"/><line x1=\"20\" y1=\"20\" x2=\"200\" y2=\"20\"/><line x1=\"200\" y1=\"20\" x2=\"200\" y2=\"200\"/><line x1=\"200\" y1=\"200\" x2=\"20\" y2=\"200\"/><line x1=\"20\" y1=\"200\" x2=\"20\" y2=\"20\"/><line x1=\"110\" y1=\"20\" x2=\"20\" y2=\"200\"/><line x1=\"200\" y1=\"20\" x2=\"110\" y2=\"200\"/><line x1=\"20\" y1=\"20\" x2=\"200\" y2=\"200\"/><text x=\"10\" y=\"16\" stroke=\"none\" fill=\"#222\">Q</text><text x=\"105\" y=\"16\" stroke=\"none\" fill=\"#222\">U</text><text x=\"203\" y=\"16\" stroke=\"none\" fill=\"#222\">R</text><text x=\"8\" y=\"212\" stroke=\"none\" fill=\"#222\">P</text><text x=\"106\" y=\"216\" stroke=\"none\" fill=\"#222\">T</text><text x=\"203\" y=\"212\" stroke=\"none\" fill=\"#222\">S</text></svg>",
  stem: "In the figure shown, $PQRS$ is a square, $T$ is the midpoint of side $PS$, and $U$ is the midpoint of side $QR$. The area of the shaded region is what fraction of the area of square $PQRS$?",
  choices: ["$\\dfrac{1}{8}$", "$\\dfrac{1}{6}$", "$\\dfrac{1}{5}$", "$\\dfrac{1}{4}$", "$\\dfrac{1}{3}$"],
  answer: 3,
  given: 1,
  source: "PowerPrep Plus 2",
  explain: "Put coordinates on it: $P(0,0)$, $S(1,0)$, $R(1,1)$, $Q(0,1)$, so $T(\\tfrac12,0)$ and $U(\\tfrac12,1)$. The three drawn segments are $QS$, $UP$, and $RT$. The shaded region has corners $P(0,0)$, $T(\\tfrac12,0)$, then $RT$ meets $QS$ at $(\\tfrac23,\\tfrac13)$, and $QS$ meets $UP$ at $(\\tfrac13,\\tfrac23)$. Shoelace on those four points gives area $\\tfrac14$ of the square.",
  trap: "Eyeballing fractions of a busy figure is a losing game &mdash; $\\tfrac16$ looks plausible. The reliable move: drop coordinates with the square as a unit square, find each intersection point by solving two line equations, and shoelace the region. Two minutes, no guessing." },
 {
  id: "sq-midpoints-1",
  topic: "Areas from midpoints in a square",
  variant: 1,
  type: "mc",
  ts: 1787340000004,
  figure: "<svg class=\"fig\" width=\"230\" height=\"230\" viewBox=\"0 0 230 230\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"14\"><polygon points=\"20,200 110,200 80,140\" fill=\"#cfcfcf\" stroke=\"none\"/><line x1=\"20\" y1=\"20\" x2=\"200\" y2=\"20\"/><line x1=\"200\" y1=\"20\" x2=\"200\" y2=\"200\"/><line x1=\"200\" y1=\"200\" x2=\"20\" y2=\"200\"/><line x1=\"20\" y1=\"200\" x2=\"20\" y2=\"20\"/><line x1=\"20\" y1=\"20\" x2=\"110\" y2=\"200\"/><line x1=\"20\" y1=\"200\" x2=\"200\" y2=\"20\"/><text x=\"8\" y=\"16\" stroke=\"none\" fill=\"#222\">D</text><text x=\"203\" y=\"16\" stroke=\"none\" fill=\"#222\">C</text><text x=\"8\" y=\"212\" stroke=\"none\" fill=\"#222\">A</text><text x=\"203\" y=\"212\" stroke=\"none\" fill=\"#222\">B</text><text x=\"104\" y=\"216\" stroke=\"none\" fill=\"#222\">M</text></svg>",
  stem: "In the figure shown, $ABCD$ is a square and $M$ is the midpoint of side $AB$. Segments $DM$ and $AC$ are drawn. The area of the shaded region is what fraction of the area of square $ABCD$?",
  choices: ["$\\dfrac{1}{16}$", "$\\dfrac{1}{12}$", "$\\dfrac{1}{8}$", "$\\dfrac{1}{6}$", "$\\dfrac{1}{4}$"],
  answer: 1,
  explain: "Coordinates: $A(0,0)$, $B(1,0)$, $C(1,1)$, $D(0,1)$, $M(\\tfrac12,0)$. $DM$ meets $AC$ at $(\\tfrac13,\\tfrac13)$. The shaded triangle $A$, $M$, $(\\tfrac13,\\tfrac13)$ has base $\\tfrac12$ and height $\\tfrac13$: area $= \\tfrac12\\cdot\\tfrac12\\cdot\\tfrac13 = \\tfrac{1}{12}$.",
  trap: "Same method: coordinates, intersection, then area. The height of the triangle is the $y$-coordinate of the intersection point, not a length you can read off the picture." },
 {
  id: "graph-shift-0",
  topic: "Horizontal shifts of a graph",
  variant: 0,
  type: "qc",
  ts: 1787340000005,
  stem: "In the $xy$-plane, the graph of the function $y = g(x)$ intersects the $x$-axis at 3 points.",
  qa: "The number of points at which the graph of the function $y = g(x-5)$ intersects the $x$-axis",
  qb: "$3$",
  answer: 2,
  given: 3,
  source: "PowerPrep Plus 2",
  explain: "Replacing $x$ with $x-5$ slides the whole graph 5 units to the right. Every $x$-intercept slides right with it &mdash; none appear, none disappear. Still 3 crossings. Equal.",
  trap: "D is tempting because you don&rsquo;t know what $g$ is. But you don&rsquo;t need to: a horizontal shift moves every point the same way, so the <em>count</em> of intercepts can&rsquo;t change, whatever the function looks like. &ldquo;Unknown function&rdquo; does not automatically mean &ldquo;cannot be determined.&rdquo;" },
 {
  id: "graph-shift-1",
  topic: "Horizontal shifts of a graph",
  variant: 1,
  type: "qc",
  ts: 1787340000006,
  stem: "In the $xy$-plane, the graph of the function $y = f(x)$ intersects the $x$-axis at 4 points.",
  qa: "The number of points at which the graph of $y = f(x+3)$ intersects the $x$-axis",
  qb: "$4$",
  answer: 2,
  explain: "$f(x+3)$ is the graph shifted 3 left. The four crossings shift left too. Equal.",
  trap: "Shifts (left, right, and also up-down? careful &mdash; a <em>vertical</em> shift CAN change the count). Horizontal only slides the crossings." },
 {
  id: "factors-qc-0",
  topic: "Factors: k need not be the product",
  variant: 0,
  type: "qc",
  ts: 1787340000007,
  stem: "$k$ and $n$ are positive integers.<br>$n$ and $n+2$ are factors of $k$.",
  qa: "$\\dfrac{k}{n}$",
  qb: "$n+2$",
  answer: 3,
  given: 0,
  source: "PowerPrep Plus 2",
  explain: "Try small cases. $n=1$: then $1$ and $3$ divide $k$. If $k=3$: $\\frac{k}{n}=3 = n+2$ (equal). If $k=6$: $6 > 3$ (A greater). $n=2$: $2$ and $4$ divide $k$, and $k=4$ works: $\\frac{k}{n} = 2 < 4$ (B greater). All three outcomes are possible, so D.",
  trap: "The instinct is $k = n(n+2)$, which forces A or C. But $k$ only needs to be a <em>common multiple</em> of $n$ and $n+2$ &mdash; and when both are even, the least common multiple is half the product ($n=2$: lcm of 2 and 4 is 4, not 8). Whenever a QC says &ldquo;factors of,&rdquo; hunt for the smallest legal $k$, not the obvious one." },
 {
  id: "factors-qc-1",
  topic: "Factors: k need not be the product",
  variant: 1,
  type: "qc",
  ts: 1787340000008,
  stem: "$m$ and $j$ are positive integers.<br>$j$ and $j+3$ are factors of $m$.",
  qa: "$\\dfrac{m}{j}$",
  qb: "$j+3$",
  answer: 3,
  explain: "$j=3$: $3$ and $6$ divide $m$. $m=6$: $\\frac{m}{j}=2<6$ (B). $m=18$: $6=6$ (C). $m=36$: $12>6$ (A). D.",
  trap: "When $j$ and $j+3$ share a factor of 3, the lcm is a third of the product. Smallest legal $m$ first." },
 {
  id: "zero-product-0",
  topic: "Products of consecutive integers through zero",
  variant: 0,
  type: "qc",
  ts: 1787340000009,
  stem: "$n$ is a negative integer, and $p$ is a positive integer.",
  qa: "The product of the integers from $n$ to $p$",
  qb: "$0$",
  answer: 2,
  given: 1,
  source: "PowerPrep Plus 2",
  explain: "&ldquo;From $n$ to $p$&rdquo; means every integer in between, and since $n<0<p$, the list includes $0$. Any product with a factor of $0$ is $0$. Equal.",
  trap: "The negatives pull the eye &mdash; &ldquo;some negatives times positives, probably negative, so B.&rdquo; But scan the list itself before reasoning about signs: zero sits in the middle and flattens everything. On any &ldquo;product of consecutive integers&rdquo; question, check for a zero first." },
 {
  id: "zero-product-1",
  topic: "Products of consecutive integers through zero",
  variant: 1,
  type: "qc",
  ts: 1787340000010,
  stem: "$a$ is a negative integer, and $b$ is a positive integer.",
  qa: "The product of the integers from $a$ to $b$",
  qb: "$a \\cdot b$",
  answer: 0,
  explain: "Quantity A includes the factor $0$, so it equals $0$. Quantity B is negative times positive, which is negative. $0 >$ negative: A.",
  trap: "Same zero check &mdash; but this time it decides the comparison instead of tying it." },
 {
  id: "percentile-0",
  topic: "Percentile rank vs. distance from the mean",
  variant: 0,
  type: "qc",
  ts: 1787340000011,
  stem: "<table style=\"border-collapse:collapse;margin:0 auto 10px;font-size:15px\"><tr><th style=\"border:1px solid #444;padding:4px 10px\">Test</th><th style=\"border:1px solid #444;padding:4px 10px\">Class Mean Score</th><th style=\"border:1px solid #444;padding:4px 10px\">Neva&rsquo;s Score</th><th style=\"border:1px solid #444;padding:4px 10px\">Neva&rsquo;s Percentile Rank</th></tr><tr><td style=\"border:1px solid #444;padding:4px 10px\">History</td><td style=\"border:1px solid #444;padding:4px 10px;text-align:center\">74</td><td style=\"border:1px solid #444;padding:4px 10px;text-align:center\">80</td><td style=\"border:1px solid #444;padding:4px 10px;text-align:center\">85</td></tr><tr><td style=\"border:1px solid #444;padding:4px 10px\">Biology</td><td style=\"border:1px solid #444;padding:4px 10px;text-align:center\">68</td><td style=\"border:1px solid #444;padding:4px 10px;text-align:center\">80</td><td style=\"border:1px solid #444;padding:4px 10px;text-align:center\">$n$</td></tr></table>",
  qa: "$n$",
  qb: "$85$",
  answer: 3,
  given: 0,
  source: "PowerPrep Plus 2",
  explain: "Percentile rank depends on how many classmates scored below her &mdash; the whole distribution &mdash; not on how far she is above the mean. In Biology she is further above the mean, but if lots of students clustered just under 80 her percentile could be lower; if the class spread out, higher. Both directions are possible: D.",
  trap: "&ldquo;12 above the mean beats 6 above the mean&rdquo; assumes the two classes have the same shape, which nothing guarantees. A mean tells you almost nothing about a percentile. When a QC mixes means with percentiles or medians, the answer is usually D unless the distribution is pinned down." },
 {
  id: "percentile-1",
  topic: "Percentile rank vs. distance from the mean",
  variant: 1,
  type: "qc",
  ts: 1787340000012,
  stem: "On Quiz 1, the class mean was 70 and Dario scored 82, placing him at the 90th percentile. On Quiz 2, the class mean was 60 and Dario scored 82, placing him at the $r$th percentile.",
  qa: "$r$",
  qb: "$90$",
  answer: 3,
  explain: "Being further above the mean on Quiz 2 says nothing certain about his rank &mdash; that depends on where everyone else landed. D.",
  trap: "Mean and percentile measure different things; one cannot be converted into the other." },
 {
  id: "wavg-groups-0",
  topic: "Weighted averages: two groups combined",
  variant: 0,
  type: "mc",
  ts: 1787340000013,
  stem: "The average (arithmetic mean) age of the people in group $G$ is 41 years, and the average age of the people in group $H$ is 36 years. The average age of the people in the two groups combined is 38 years. If no person is in both groups, what fraction of the people in the two groups combined are in group $H$?",
  choices: ["$\\dfrac{2}{5}$", "$\\dfrac{1}{2}$", "$\\dfrac{3}{5}$", "$\\dfrac{2}{3}$", "$\\dfrac{3}{4}$"],
  answer: 2,
  given: 3,
  source: "PowerPrep Plus 2",
  explain: "Let $x$ be the fraction in $H$. Then $36x + 41(1-x) = 38$, so $41 - 5x = 38$ and $x = \\tfrac{3}{5}$. Shortcut: the combined mean 38 sits 2 away from 36 and 3 away from 41, so the groups balance in ratio $3:2$ &mdash; and the <em>bigger</em> share goes to the group whose mean is <em>closer</em> to 38. That&rsquo;s $H$: $\\tfrac{3}{5}$.",
  trap: "$\\tfrac{2}{3}$ comes from the see-saw distances ($2$ and $3$) assembled the wrong way round. The group closer to the combined average is the heavier one. If in doubt, skip the shortcut and write the one-line equation &mdash; it takes 20 seconds and can&rsquo;t flip on you." },
 {
  id: "wavg-groups-1",
  topic: "Weighted averages: two groups combined",
  variant: 1,
  type: "mc",
  ts: 1787340000014,
  stem: "The average score of team $X$ is 50 and the average score of team $Y$ is 62. The average score of the two teams combined is 58. If no one is on both teams, what fraction of the combined group is on team $Y$?",
  choices: ["$\\dfrac{1}{3}$", "$\\dfrac{1}{2}$", "$\\dfrac{3}{5}$", "$\\dfrac{2}{3}$", "$\\dfrac{3}{4}$"],
  answer: 3,
  explain: "$62y + 50(1-y) = 58 \\Rightarrow 12y = 8 \\Rightarrow y = \\tfrac{2}{3}$. (Distances: 58 is 8 from 50 and 4 from 62, ratio $8{:}4 = 2{:}1$ in favor of $Y$.)",
  trap: "Closer mean = bigger group. Check: the combined 58 leans toward 62, so $Y$ must dominate." },
 {
  id: "coord-area-0",
  topic: "Areas of coordinate quadrilaterals",
  variant: 0,
  type: "mc",
  ts: 1787340000015,
  figure: "<svg class=\"fig\" width=\"230\" height=\"220\" viewBox=\"0 0 230 220\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"13\"><line x1=\"30\" y1=\"200\" x2=\"30\" y2=\"20\"/><line x1=\"10\" y1=\"190\" x2=\"210\" y2=\"190\"/><polygon points=\"30,100 150,40 120,190 30,190\" fill=\"none\" stroke=\"#222\"/><text x=\"12\" y=\"98\" stroke=\"none\" fill=\"#222\">R(0, 3)</text><text x=\"152\" y=\"38\" stroke=\"none\" fill=\"#222\">S(4, 5)</text><text x=\"122\" y=\"206\" stroke=\"none\" fill=\"#222\">T(3, 0)</text><text x=\"16\" y=\"206\" stroke=\"none\" fill=\"#222\">O</text><text x=\"214\" y=\"196\" stroke=\"none\" fill=\"#222\">x</text></svg>",
  stem: "In the $xy$-plane shown, what is the area of quadrilateral $RSTO$?",
  choices: ["$15$", "$13\\tfrac{1}{2}$", "$11\\tfrac{1}{4}$", "$10\\tfrac{1}{2}$", "$7$"],
  answer: 1,
  given: 1,
  source: "PowerPrep Plus 2 (guessed, got lucky)",
  explain: "Shoelace around $O(0,0) \\to T(3,0) \\to S(4,5) \\to R(0,3)$: sum of $x_iy_{i+1} - x_{i+1}y_i$ gives $0 + 15 + 12 + 0 = 27$, and half of that is $13\\tfrac12$. Alternative: split into triangles $OTS$ (area $\\tfrac12\\cdot3\\cdot5 = 7.5$) and $OSR$ (area $\\tfrac12\\cdot3\\cdot4 = 6$): total $13.5$.",
  trap: "This one was a lucky guess, so the job is to own a method. Shoelace: list the vertices going around the shape once, multiply crosswise, subtract, halve. Or slice the shape into triangles from one vertex. Either way, no eyeballing." },
 {
  id: "coord-area-1",
  topic: "Areas of coordinate quadrilaterals",
  variant: 1,
  type: "mc",
  ts: 1787340000016,
  figure: "<svg class=\"fig\" width=\"230\" height=\"220\" viewBox=\"0 0 230 220\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"13\"><line x1=\"30\" y1=\"200\" x2=\"30\" y2=\"20\"/><line x1=\"10\" y1=\"190\" x2=\"215\" y2=\"190\"/><polygon points=\"30,190 150,190 180,70 30,130\" fill=\"none\" stroke=\"#222\"/><text x=\"16\" y=\"206\" stroke=\"none\" fill=\"#222\">O</text><text x=\"140\" y=\"206\" stroke=\"none\" fill=\"#222\">A(4, 0)</text><text x=\"176\" y=\"66\" stroke=\"none\" fill=\"#222\">B(5, 4)</text><text x=\"12\" y=\"126\" stroke=\"none\" fill=\"#222\">C(0, 2)</text><text x=\"219\" y=\"196\" stroke=\"none\" fill=\"#222\">x</text></svg>",
  stem: "In the $xy$-plane shown, what is the area of quadrilateral $OABC$?",
  choices: ["$11$", "$12$", "$13$", "$14$", "$15$"],
  answer: 2,
  explain: "Shoelace on $O(0,0) \\to A(4,0) \\to B(5,4) \\to C(0,2)$: $0 + 16 + 10 + 0 = 26$, half is $13$.",
  trap: "Keep the vertices in order around the shape &mdash; skipping around the quadrilateral breaks the shoelace." },
 {
  id: "digit-count-0",
  topic: "Counting integers by digit conditions",
  variant: 0,
  type: "mc",
  ts: 1787340000017,
  stem: "How many integers $n$ between 100 and 299 are there such that the hundreds digit of $n$ is less than the tens digit of $n$ and the tens digit of $n$ is less than the units digit of $n$?",
  choices: ["$48$", "$49$", "$50$", "$51$", "$52$"],
  answer: 1,
  given: 3,
  source: "PowerPrep Plus 2",
  explain: "The hundreds digit is 1 or 2. Once you pick the two remaining digits, their order is forced (tens $<$ units), so just count the choices. Hundreds $=1$: pick 2 digits from $\\{2,\\ldots,9\\}$: $\\binom{8}{2} = 28$. Hundreds $=2$: pick 2 from $\\{3,\\ldots,9\\}$: $\\binom{7}{2} = 21$. Total $28+21 = 49$.",
  trap: "Counting by listing invites off-by-a-few errors ($51$ is a miscount, not a concept gap). The structural insight: strictly increasing digits means <em>choosing</em> a set, not arranging one &mdash; each choice of digits gives exactly one valid number, so it&rsquo;s a combination count, $\\binom{n}{k}$, not a list." },
 {
  id: "digit-count-1",
  topic: "Counting integers by digit conditions",
  variant: 1,
  type: "mc",
  ts: 1787340000018,
  stem: "How many integers $n$ between 200 and 399 are there such that the hundreds digit of $n$ is less than the tens digit of $n$ and the tens digit of $n$ is less than the units digit of $n$?",
  choices: ["$34$", "$35$", "$36$", "$38$", "$42$"],
  answer: 2,
  explain: "Hundreds $=2$: $\\binom{7}{2}=21$. Hundreds $=3$: $\\binom{6}{2}=15$. Total $36$.",
  trap: "Same structure: increasing digits = choose the set, the order comes free." },
 {
  id: "abs-count-0",
  topic: "Counting solutions of absolute-value equations",
  variant: 0,
  type: "ne",
  ts: 1787340000019,
  stem: "How many different numbers $x$ satisfy the equation $|x^2 - 5x| = 1$?",
  answer: "4",
  given: "2",
  source: "PowerPrep Plus 2",
  explain: "The absolute value splits into two separate equations: $x^2 - 5x = 1$ and $x^2 - 5x = -1$. Check each discriminant: $x^2-5x-1=0$ has $25+4 = 29 > 0$ (two roots); $x^2-5x+1=0$ has $25-4=21>0$ (two roots). No root satisfies both, so $2+2 = 4$ solutions.",
  trap: "Answering 2 treats $|x^2-5x|=1$ as one quadratic. An absolute value equal to a positive number always means <em>two</em> equations, and each quadratic can contribute up to two roots &mdash; so the count can be 0, 1, 2, 3, or 4. Discriminants decide; you never need the actual roots." },
 {
  id: "abs-count-1",
  topic: "Counting solutions of absolute-value equations",
  variant: 1,
  type: "ne",
  ts: 1787340000020,
  stem: "How many different numbers $x$ satisfy the equation $|x^2 - 6x| = 9$?",
  answer: "3",
  explain: "$x^2-6x = 9$: discriminant $36+36 = 72 > 0$, two roots. $x^2 - 6x = -9$: $x^2-6x+9 = (x-3)^2 = 0$, exactly one root. Total $3$.",
  trap: "The count isn&rsquo;t always 4 &mdash; a zero discriminant gives a single (repeated) root. Check both branches every time." },

 /* ==== Added 2026-08-21 (batch 2) — PowerPrep + worksheet misses ==== */
 {
  id: "compound-halfrate-0",
  topic: "Compound interest: the per-period rate",
  variant: 0,
  type: "mc",
  ts: 1787345000001,
  stem: "An investor wants \\$8,000 to grow to at least \\$8,600 in one year, in an account paying $r$ percent annual interest compounded semiannually. To the nearest 0.1, what is the least value of $r$ that achieves this?",
  choices: ["$3.7$", "$7.3$", "$7.4$", "$7.5$", "$8.6$"],
  answer: 2,
  given: 0,
  source: "LCC Interest worksheet, Challenge 1",
  explain: "Semiannual compounding means two periods per year at $\\tfrac{r}{2}$ percent each: $8000\\left(1+\\tfrac{r}{200}\\right)^2 \\ge 8600$, so $\\left(1+\\tfrac{r}{200}\\right)^2 \\ge 1.075$. Square root: $1+\\tfrac{r}{200} \\ge 1.0368\\ldots$, so $r \\ge 7.36\\ldots$ Check the choices: $r=7.3$ gives $1.0743$ (short); $r=7.4$ gives $1.0754$ (enough). Least value: $7.4$.",
  trap: "$3.7$ is what you get by solving for the <em>per-period</em> rate and stopping. In $V = P\\left(1+\\tfrac{r}{n}\\right)^{nt}$, $r$ is always the annual rate; the halving already lives inside the formula. If your answer is suspiciously close to half of another choice, that&rsquo;s the alarm." },
 {
  id: "compound-halfrate-1",
  topic: "Compound interest: the per-period rate",
  variant: 1,
  type: "mc",
  ts: 1787345000002,
  stem: "An investor wants \\$5,000 to grow to at least \\$5,300 in one year, in an account paying $r$ percent annual interest compounded semiannually. To the nearest 0.1, what is the least value of $r$ that achieves this?",
  choices: ["$2.9$", "$5.8$", "$5.9$", "$6.0$", "$6.1$"],
  answer: 3,
  explain: "$\\left(1+\\tfrac{r}{200}\\right)^2 \\ge 1.06$. At $r=5.9$: $1.0295^2 = 1.0599$ &mdash; just short. At $r=6.0$: $1.03^2 = 1.0609$. Least: $6.0$.",
  trap: "Same alarm: $2.9$ is the per-period rate. And $5.9$ fails by a hair &mdash; test the boundary choice rather than rounding past it." },
 {
  id: "compound-years-0",
  topic: "Compound growth year over year",
  variant: 0,
  type: "qc",
  ts: 1787345000003,
  stem: "An account earns interest at $r\\%$ compounded annually, where $r > 0$.",
  qa: "Interest earned during the second year",
  qb: "Interest earned during the first year",
  answer: 0,
  given: 3,
  source: "LCC Interest worksheet quiz",
  explain: "Year 1 interest is $P\\cdot\\tfrac{r}{100}$. During year 2 the balance is bigger ($P(1+\\tfrac{r}{100})$), so year-2 interest is the year-1 interest times $(1+\\tfrac{r}{100})$, which is greater since $r>0$. A.",
  trap: "D feels safe because $P$ and $r$ are unknown. But the comparison doesn&rsquo;t need them: whatever they are, year 2 starts from a larger balance, so it earns more. Unknown numbers with a <em>structural</em> relationship is exactly when the answer is not D." },
 {
  id: "compound-years-1",
  topic: "Compound growth year over year",
  variant: 1,
  type: "qc",
  ts: 1787345000004,
  stem: "An account earns interest at $r\\%$ compounded annually, where $r > 0$.",
  qa: "Interest earned during the third year",
  qb: "Interest earned during the second year",
  answer: 0,
  explain: "Each year&rsquo;s interest is the previous year&rsquo;s interest times $(1+\\tfrac{r}{100})$. Year 3 beats year 2. A.",
  trap: "Compounding makes each year&rsquo;s interest a fixed multiple of the last &mdash; no need to know $P$ or $r$." },
 {
  id: "swap-unknowns-0",
  topic: "QC: symmetric-looking, unrelated unknowns",
  variant: 0,
  type: "qc",
  ts: 1787345000005,
  stem: "$m$, $n$, and $q$ are positive numbers, with no relationship given.",
  qa: "The total weight of $m$ peanuts with a weight of $n+3$ mg each",
  qb: "The total weight of $q$ almonds with a weight of $m+3$ mg each",
  answer: 3,
  given: 1,
  source: "PowerPrep",
  explain: "Quantity A is $m(n+3)$; Quantity B is $q(m+3)$. Nothing links $q$ to $m$ and $n$. Try $m=n=q=1$: both are $4$ (equal). Make $q$ huge: B wins. Make $m$ and $n$ huge with $q=1$: A wins. D.",
  trap: "The two quantities <em>look</em> like mirror images, which nudges you to compare them piece by piece. But the letters aren&rsquo;t connected by any equation &mdash; the symmetry is cosmetic. With no relationship given, test values aimed at making each side win." },
 {
  id: "swap-unknowns-1",
  topic: "QC: symmetric-looking, unrelated unknowns",
  variant: 1,
  type: "qc",
  ts: 1787345000006,
  stem: "$a$, $b$, and $c$ are positive numbers, with no relationship given.",
  qa: "The total cost of $a$ books at $b+5$ dollars each",
  qb: "The total cost of $c$ books at $a+5$ dollars each",
  answer: 3,
  explain: "$a(b+5)$ vs $c(a+5)$ with $c$ free: each side can win, and $a=b=c$ makes them equal. D.",
  trap: "Cosmetic symmetry. No connecting equation means test extremes." },
 {
  id: "crate-range-0",
  topic: "Range of the remaining value (mean + bounds)",
  variant: 0,
  type: "mc",
  ts: 1787345000007,
  stem: "The average (arithmetic mean) weight of 5 crates is 250 pounds. The 2 lightest crates weigh between 200 and 205 pounds each, inclusive, and the 2 heaviest crates weigh between 300 and 310 pounds each, inclusive. If the weight of the fifth crate is $x$ pounds, then $x$ is expressed by which of the following?",
  choices: ["$220 \\le x \\le 250$", "$230 \\le x \\le 260$", "$240 \\le x \\le 270$", "$250 \\le x \\le 270$", "$260 \\le x \\le 280$"],
  answer: 0,
  given: 3,
  source: "PowerPrep",
  explain: "Total weight is $5 \\times 250 = 1250$, so $x = 1250 - (\\text{two lightest}) - (\\text{two heaviest})$. $x$ is smallest when the others are heaviest: $1250 - 2(205) - 2(310) = 220$. $x$ is largest when the others are lightest: $1250 - 2(200) - 2(300) = 250$. So $220 \\le x \\le 250$.",
  trap: "The endpoints run <em>opposite</em> to instinct: the other crates at their MAX push $x$ to its MIN. Pairing max with max produces a shifted range like $250$&ndash;$270$. Fix the total first (mean $\\times$ count), then push the knowns to their extremes and watch $x$ move the other way." },
 {
  id: "crate-range-1",
  topic: "Range of the remaining value (mean + bounds)",
  variant: 1,
  type: "mc",
  ts: 1787345000008,
  stem: "The average (arithmetic mean) weight of 4 boxes is 100 pounds. The 2 lightest boxes weigh between 70 and 75 pounds each, inclusive, and the heaviest box weighs between 140 and 150 pounds, inclusive. If the weight of the fourth box is $x$ pounds, then $x$ is expressed by which of the following?",
  choices: ["$90 \\le x \\le 110$", "$100 \\le x \\le 120$", "$110 \\le x \\le 130$", "$120 \\le x \\le 140$", "$130 \\le x \\le 150$"],
  answer: 1,
  explain: "Total $= 400$. Min $x = 400 - 2(75) - 150 = 100$; max $x = 400 - 2(70) - 140 = 120$.",
  trap: "Others at max $\\Rightarrow$ $x$ at min. Total first, then extremes." },
 {
  id: "recur-seq-0",
  topic: "Recursive sequences: run the recipe",
  variant: 0,
  type: "mc",
  ts: 1787345000009,
  stem: "In a certain sequence, $s_1, s_2, \\ldots, s_x$, where $s_1 = 2$, $s_2 = 2$, $s_3 = 2$, and for $x \\ge 4$, $s_x = 2s_{x-1} + s_{x-2}$, what is the value of $s_6$?",
  choices: ["$30$", "$34$", "$37$", "$38$", "$40$"],
  answer: 1,
  source: "PowerPrep — reviewed together in session",
  explain: "Run it forward one term at a time: $s_4 = 2s_3 + s_2 = 2(2)+2 = 6$; $s_5 = 2s_4 + s_3 = 12 + 2 = 14$; $s_6 = 2s_5 + s_4 = 28 + 6 = 34$.",
  trap: "The only trap is bookkeeping: $s_{x-1}$ is the term <em>right before</em>, $s_{x-2}$ two before. Write the three known terms in a row and extend the row &mdash; never juggle it in your head." },
 {
  id: "recur-seq-1",
  topic: "Recursive sequences: run the recipe",
  variant: 1,
  type: "mc",
  ts: 1787345000010,
  stem: "In a certain sequence, $t_1 = 1$, $t_2 = 1$, $t_3 = 1$, and for $x \\ge 4$, $t_x = 2t_{x-1} + t_{x-2}$. What is the value of $t_6$?",
  choices: ["$15$", "$16$", "$17$", "$18$", "$21$"],
  answer: 2,
  explain: "$t_4 = 2+1 = 3$; $t_5 = 6+1 = 7$; $t_6 = 14+3 = 17$.",
  trap: "Row of terms on paper; extend one at a time." },
 {
  id: "system-constant-0",
  topic: "Systems with a constant: does c get pinned?",
  variant: 0,
  type: "qc",
  ts: 1787345000011,
  stem: "$$2x + cy = 10$$ $$6x + 2cy = 40$$ The system of equations shown has a solution, where $c$ is a constant.",
  qa: "$c$",
  qb: "$1$",
  answer: 3,
  source: "PowerPrep — reviewed together in session",
  explain: "Eliminate: multiply the first equation by 3 to get $6x + 3cy = 30$; subtract the second: $cy = -10$. Then $2x = 10 - cy = 20$, so $x = 10$. For <em>any</em> $c \\ne 0$, choosing $y = -10/c$ solves the system. $c$ could be $5$ (A) or $-2$ (B) &mdash; nothing pins it. D.",
  trap: "&ldquo;Has a solution&rdquo; sounds like it should force $c$ to one value, but here it only rules out $c = 0$. Do the elimination and see what actually gets determined: $x$ is pinned, $c$ is free. A constant in a QC is only comparable if the algebra truly locks it." },
 {
  id: "system-constant-1",
  topic: "Systems with a constant: does c get pinned?",
  variant: 1,
  type: "qc",
  ts: 1787345000012,
  stem: "$$x + cy = 5$$ $$3x + 3cy = 15$$ The system of equations shown has a solution, where $c$ is a constant.",
  qa: "$c$",
  qb: "$1$",
  answer: 3,
  explain: "The second equation is 3 times the first, so the system holds for every $c$ (with a suitable $y$). $c$ is unconstrained: D.",
  trap: "Check whether the second equation adds new information before assuming it pins anything down." },
 {
  id: "simple-month-0",
  topic: "Simple interest: annual rate, fractional time",
  variant: 0,
  type: "mc",
  ts: 1787345000013,
  stem: "A total of \\$36,000 was invested for one month in a new money market account that paid simple annual interest at the rate of $r$ percent. If the investment earned \\$360 in interest for the month, what is the value of $r$?",
  choices: ["$10.0$", "$10.5$", "$11.0$", "$12.0$", "$12.5$"],
  answer: 3,
  source: "PowerPrep — reviewed together in session",
  explain: "Simple interest: $I = P \\cdot \\tfrac{r}{100} \\cdot t$, with $t$ in <em>years</em>. One month is $t = \\tfrac{1}{12}$: $360 = 36000 \\cdot \\tfrac{r}{100} \\cdot \\tfrac{1}{12} = 30r$, so $r = 12$.",
  trap: "The slip to guard against is the time unit: the rate is annual, so one month is $t=\\tfrac1{12}$, and dropping or misplacing that factor of 12 scales the answer up or down by 12 (that&rsquo;s where stray answers like $1.2$ come from). Write the formula with units before plugging in." },
 {
  id: "simple-month-1",
  topic: "Simple interest: annual rate, fractional time",
  variant: 1,
  type: "mc",
  ts: 1787345000014,
  stem: "A total of \\$24,000 was invested for one month in an account that paid simple annual interest at the rate of $r$ percent. If the investment earned \\$160 in interest for the month, what is the value of $r$?",
  choices: ["$0.7$", "$7.5$", "$8.0$", "$9.6$", "$12.0$"],
  answer: 2,
  explain: "$160 = 24000 \\cdot \\tfrac{r}{100} \\cdot \\tfrac{1}{12} = 20r$, so $r = 8$.",
  trap: "$0.7$ is the missing-$\\tfrac1{12}$ answer. Annual rate, time in years." },
 {
  id: "abs-ranges-0",
  topic: "Absolute-value ranges: signs are free",
  variant: 0,
  type: "mc",
  ts: 1787345000015,
  stem: "$$6 \\le |x| \\le 8$$ $$1 \\le |y| \\le 2$$ $$3 \\le |z| \\le 4$$ If $x$, $y$, and $z$ satisfy the inequalities shown, what is the least possible value of $|x+y+z|$?",
  choices: ["$0$", "$1$", "$2$", "$3$", "$4$"],
  answer: 0,
  given: 3,
  source: "PowerPrep",
  explain: "$|x| \\in [6,8]$ means $x$ itself lives in $[6,8]$ <em>or</em> $[-8,-6]$ &mdash; the sign is free. So ask directly: can the three pieces cancel to 0? Since $6 = 2 + 4$, take $x = 6$, $y = -2$, $z = -4$: sum is $0$, and $|0| = 0$.",
  trap: "Working only with positive values (or shuffling combinations without a target) leaves you stranded on a nonzero answer like 3. On any &ldquo;least possible $|\\ldots|$&rdquo; question, the first move is: <em>can it be exactly zero?</em> Check whether one value can equal the sum of the others." },
 {
  id: "abs-ranges-1",
  topic: "Absolute-value ranges: signs are free",
  variant: 1,
  type: "mc",
  ts: 1787345000016,
  stem: "$$4 \\le |a| \\le 6$$ $$2 \\le |b| \\le 3$$ $$1 \\le |c| \\le 2$$ If $a$, $b$, and $c$ satisfy the inequalities shown, what is the least possible value of $|a+b+c|$?",
  choices: ["$0$", "$1$", "$2$", "$3$", "$4$"],
  answer: 0,
  explain: "$a = 4$, $b = -3$, $c = -1$: the sum is $0$.",
  trap: "Can it be exactly zero? $4 = 3+1$ says yes." },
 {
  id: "arc-vs-line-0",
  topic: "Arc length vs. straight length",
  variant: 0,
  type: "qc",
  ts: 1787345000017,
  figure: "<svg class=\"fig\" width=\"220\" height=\"220\" viewBox=\"0 0 220 220\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"14\"><circle cx=\"110\" cy=\"110\" r=\"80\"/><polygon points=\"70,41 150,41 190,110 150,179 70,179 30,110\" stroke=\"#222\" fill=\"none\"/><circle cx=\"110\" cy=\"110\" r=\"2\" fill=\"#222\"/><text x=\"60\" y=\"34\" stroke=\"none\" fill=\"#222\">Q</text><text x=\"152\" y=\"34\" stroke=\"none\" fill=\"#222\">R</text><text x=\"196\" y=\"115\" stroke=\"none\" fill=\"#222\">S</text><text x=\"152\" y=\"196\" stroke=\"none\" fill=\"#222\">T</text><text x=\"56\" y=\"196\" stroke=\"none\" fill=\"#222\">U</text><text x=\"14\" y=\"115\" stroke=\"none\" fill=\"#222\">P</text><text x=\"114\" y=\"106\" stroke=\"none\" fill=\"#222\">O</text></svg>",
  stem: "In the figure shown, hexagon $PQRSTU$ is equilateral and is inscribed in the circle with center $O$.",
  qa: "The length of diameter $UOR$",
  qb: "The length of arc $RST$",
  answer: 1,
  given: 0,
  source: "PowerPrep",
  explain: "Each side of the hexagon spans a $60°$ arc. Arc $RST$ runs $R \\to S \\to T$: two sides, so $120°$, which is $\\tfrac{120}{360} \\cdot 2\\pi r = \\tfrac{2\\pi r}{3} \\approx 2.09r$. The diameter is $2r$. The arc wins by a little: B.",
  trap: "They look about the same on the figure, and the diameter &ldquo;feels&rdquo; long because it crosses the whole circle. Write both in terms of $r$: $\\tfrac{2\\pi}{3} \\approx 2.09 > 2$. Never settle a close QC by eye when both sides can be computed." },
 {
  id: "arc-vs-line-1",
  topic: "Arc length vs. straight length",
  variant: 1,
  type: "qc",
  ts: 1787345000018,
  figure: "<svg class=\"fig\" width=\"220\" height=\"220\" viewBox=\"0 0 220 220\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"14\"><circle cx=\"110\" cy=\"110\" r=\"80\"/><polygon points=\"70,41 150,41 190,110 150,179 70,179 30,110\" stroke=\"#222\" fill=\"none\"/><circle cx=\"110\" cy=\"110\" r=\"2\" fill=\"#222\"/><text x=\"60\" y=\"34\" stroke=\"none\" fill=\"#222\">Q</text><text x=\"152\" y=\"34\" stroke=\"none\" fill=\"#222\">R</text><text x=\"196\" y=\"115\" stroke=\"none\" fill=\"#222\">S</text><text x=\"152\" y=\"196\" stroke=\"none\" fill=\"#222\">T</text><text x=\"56\" y=\"196\" stroke=\"none\" fill=\"#222\">U</text><text x=\"14\" y=\"115\" stroke=\"none\" fill=\"#222\">P</text><text x=\"114\" y=\"106\" stroke=\"none\" fill=\"#222\">O</text></svg>",
  stem: "In the figure shown, hexagon $PQRSTU$ is equilateral and is inscribed in the circle with center $O$.",
  qa: "The length of arc $RS$",
  qb: "The length of side $RS$",
  answer: 0,
  explain: "A side of an inscribed equilateral hexagon equals the radius $r$; arc $RS$ spans $60°$: $\\tfrac{\\pi r}{3} \\approx 1.05r$. A.",
  trap: "An arc is always longer than its chord &mdash; the straight path is the shortest one." },
 {
  id: "pigeonhole-0",
  topic: "Worst-case (pigeonhole) counting",
  variant: 0,
  type: "mc",
  ts: 1787345000019,
  stem: "Ben has 30 pencils in a box. Each of the pencils is one of 5 different colors, and there are 6 pencils of each color. If Ben selects pencils one at a time from the box without being able to see the pencils, what is the minimum number of pencils that he must select in order to ensure that he selects at least 2 pencils of each color?",
  choices: ["$24$", "$25$", "$26$", "$27$", "$28$"],
  answer: 2,
  given: 1,
  source: "PowerPrep",
  explain: "Think like the worst-case villain: delay one color as long as possible. Draw ALL of four colors ($4 \\times 6 = 24$), then $1$ of the last color &mdash; that&rsquo;s $25$ pencils with only one of that color. One more forces the second: $26$.",
  trap: "$25$ is the moment the villain is cornered but hasn&rsquo;t surrendered: you hold one of the last color, not two. Build the worst case that still <em>fails</em>, then add one. Every &ldquo;guarantee&rdquo; problem is (worst failing case) $+\\,1$." },
 {
  id: "pigeonhole-1",
  topic: "Worst-case (pigeonhole) counting",
  variant: 1,
  type: "mc",
  ts: 1787345000020,
  stem: "A drawer has 40 marbles: 10 each of 4 different colors. Marbles are drawn one at a time without looking. What is the minimum number of marbles that must be drawn to ensure at least 3 marbles of each color?",
  choices: ["$31$", "$32$", "$33$", "$34$", "$35$"],
  answer: 2,
  explain: "Worst case: all of three colors ($30$) plus $2$ of the last &mdash; $32$ drawn, still only two of one color. The next draw settles it: $33$.",
  trap: "(Worst failing case) $+\\,1$." },
 {
  id: "circle-diam-coord-0",
  topic: "Circles in the plane: inscribed right angles",
  variant: 0,
  type: "mc",
  ts: 1787345000021,
  figure: "<svg class=\"fig\" width=\"300\" height=\"220\" viewBox=\"0 0 300 220\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"14\"><line x1=\"60\" y1=\"160\" x2=\"280\" y2=\"160\"/><line x1=\"200\" y1=\"210\" x2=\"200\" y2=\"20\"/><circle cx=\"148\" cy=\"130\" r=\"60\"/><line x1=\"200\" y1=\"160\" x2=\"96\" y2=\"100\"/><circle cx=\"96\" cy=\"100\" r=\"2.5\" fill=\"#222\"/><circle cx=\"200\" cy=\"100\" r=\"2.5\" fill=\"#222\"/><text x=\"82\" y=\"94\" stroke=\"none\" fill=\"#222\">P</text><text x=\"206\" y=\"98\" stroke=\"none\" fill=\"#222\">Q(0, 3)</text><text x=\"176\" y=\"148\" stroke=\"none\" fill=\"#222\" font-size=\"12\">60&#176;</text><text x=\"204\" y=\"176\" stroke=\"none\" fill=\"#222\">O</text><text x=\"284\" y=\"156\" stroke=\"none\" fill=\"#222\">x</text><text x=\"192\" y=\"18\" stroke=\"none\" fill=\"#222\">y</text></svg>",
  stem: "In the figure shown, $OP$ is a diameter of the circle. What is the $x$-coordinate of point $P$?",
  choices: ["$-3$", "$-6$", "$-\\sqrt{3}$", "$-2\\sqrt{3}$", "$-3\\sqrt{3}$"],
  answer: 4,
  given: 3,
  source: "PowerPrep",
  explain: "$Q$ is on the circle and $OP$ is a diameter, so the angle at $Q$ in triangle $OQP$ is a right angle (angle in a semicircle). $OQ$ runs up the $y$-axis with length 3, and the $60°$ at $O$ sits between the diameter and $OQ$. Then $\\cos 60° = \\tfrac{OQ}{OP}$, so $OP = \\tfrac{3}{1/2} = 6$, and $P = 6(\\cos 150°, \\sin 150°) = (-3\\sqrt{3},\\, 3)$. The $x$-coordinate is $-3\\sqrt{3}$.",
  trap: "$-2\\sqrt3$ comes from treating $OQ$ as the hypotenuse or misplacing the $60°$. Two anchors fix everything: a triangle inscribed on a diameter is right-angled at the third point, then it&rsquo;s plain SOH-CAH-TOA. Sanity check: $P$ must share $Q$&rsquo;s height ($y = 3$), which the wrong answers&rsquo; triangles fail." },
 {
  id: "circle-diam-coord-1",
  topic: "Circles in the plane: inscribed right angles",
  variant: 1,
  type: "mc",
  ts: 1787345000022,
  figure: "<svg class=\"fig\" width=\"300\" height=\"220\" viewBox=\"0 0 300 220\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.5\" font-family=\"Times New Roman\" font-style=\"italic\" font-size=\"14\"><line x1=\"60\" y1=\"160\" x2=\"280\" y2=\"160\"/><line x1=\"200\" y1=\"210\" x2=\"200\" y2=\"20\"/><circle cx=\"148\" cy=\"130\" r=\"60\"/><line x1=\"200\" y1=\"160\" x2=\"96\" y2=\"100\"/><circle cx=\"96\" cy=\"100\" r=\"2.5\" fill=\"#222\"/><circle cx=\"200\" cy=\"100\" r=\"2.5\" fill=\"#222\"/><text x=\"82\" y=\"94\" stroke=\"none\" fill=\"#222\">P</text><text x=\"206\" y=\"98\" stroke=\"none\" fill=\"#222\">Q(0, 2)</text><text x=\"176\" y=\"148\" stroke=\"none\" fill=\"#222\" font-size=\"12\">60&#176;</text><text x=\"204\" y=\"176\" stroke=\"none\" fill=\"#222\">O</text><text x=\"284\" y=\"156\" stroke=\"none\" fill=\"#222\">x</text><text x=\"192\" y=\"18\" stroke=\"none\" fill=\"#222\">y</text></svg>",
  stem: "In the figure shown, $OP$ is a diameter of the circle, $Q(0,2)$ is on the circle, and the angle at $O$ between $OP$ and $OQ$ measures $60°$. What is the $x$-coordinate of point $P$?",
  choices: ["$-2$", "$-4$", "$-\\sqrt{3}$", "$-2\\sqrt{3}$", "$-4\\sqrt{3}$"],
  answer: 3,
  explain: "Right angle at $Q$; $\\cos 60° = \\tfrac{OQ}{OP}$ gives $OP = 4$; $P = 4(\\cos 150°, \\sin 150°) = (-2\\sqrt3, 2)$.",
  trap: "Semicircle $\\Rightarrow$ right angle at the third point, then trig." },
 {
  id: "nested-circles-0",
  topic: "Nested circles: radii scale, areas scale squared",
  variant: 0,
  type: "mc",
  ts: 1787345000023,
  figure: "<svg class=\"fig\" width=\"200\" height=\"200\" viewBox=\"0 0 200 200\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.4\"><circle cx=\"100\" cy=\"100\" r=\"90\"/><circle cx=\"100\" cy=\"100\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"160\" cy=\"100\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"130\" cy=\"152\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"70\" cy=\"152\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"40\" cy=\"100\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"70\" cy=\"48\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"130\" cy=\"48\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/></svg>",
  stem: "In the figure shown, seven small circles of equal diameter are located inside a large circle. Each of the six outer small circles is tangent to the small circle in the center, to two other adjacent small circles, and to the large circle. If the diameter of the large circle is $D$, then the sum of the areas of the unshaded regions inside the large circle is equal to which of the following?",
  choices: ["$\\dfrac{\\pi D^2}{36}$", "$\\dfrac{\\pi D^2}{18}$", "$\\dfrac{\\pi D^2}{9}$", "$\\dfrac{\\pi D^2}{2}$", "$\\dfrac{7\\pi D^2}{4}$"],
  answer: 1,
  given: 3,
  source: "PowerPrep",
  explain: "Across the middle, three small diameters span the large one, so each small circle has diameter $\\tfrac{D}{3}$ and radius $\\tfrac{D}{6}$. Unshaded $=$ large minus seven small: $\\pi\\left(\\tfrac{D}{2}\\right)^2 - 7\\pi\\left(\\tfrac{D}{6}\\right)^2 = \\tfrac{\\pi D^2}{4} - \\tfrac{7\\pi D^2}{36} = \\tfrac{2\\pi D^2}{36} = \\tfrac{\\pi D^2}{18}$.",
  trap: "Area uses the radius <em>squared</em>: a circle with one-third the diameter has one-<em>ninth</em> the area. Convert every diameter to a radius before any area formula, and put both areas over a common denominator before subtracting." },
 {
  id: "nested-circles-1",
  topic: "Nested circles: radii scale, areas scale squared",
  variant: 1,
  type: "mc",
  ts: 1787345000024,
  figure: "<svg class=\"fig\" width=\"200\" height=\"200\" viewBox=\"0 0 200 200\" fill=\"none\" stroke=\"#222\" stroke-width=\"1.4\"><circle cx=\"100\" cy=\"100\" r=\"90\"/><circle cx=\"40\" cy=\"100\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"100\" cy=\"100\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/><circle cx=\"160\" cy=\"100\" r=\"30\" fill=\"#d9d9d9\" fill-opacity=\"0.85\"/></svg>",
  stem: "In the figure shown, three small circles of equal diameter are centered on a diameter of the large circle; each is tangent to the next, and the outer two are tangent to the large circle. If the diameter of the large circle is $D$, the total area inside the large circle but outside the small circles equals which of the following?",
  choices: ["$\\dfrac{\\pi D^2}{12}$", "$\\dfrac{\\pi D^2}{6}$", "$\\dfrac{\\pi D^2}{4}$", "$\\dfrac{\\pi D^2}{3}$", "$\\dfrac{\\pi D^2}{2}$"],
  answer: 1,
  explain: "Small radius $\\tfrac{D}{6}$: $\\tfrac{\\pi D^2}{4} - 3\\cdot\\tfrac{\\pi D^2}{36} = \\tfrac{\\pi D^2}{4} - \\tfrac{\\pi D^2}{12} = \\tfrac{\\pi D^2}{6}$.",
  trap: "Radius before area, always." },
 {
  id: "three-eq-chain-0",
  topic: "Chained equations: solve, then substitute carefully",
  variant: 0,
  type: "ne",
  ts: 1787345000025,
  stem: "If $3x + y = 2$, $3x + 2y = 0$, and $x - 2z = 1$, what is the value of $z$?<br><span style=\"font-size:15px\">Give your answer as a fraction.</span>",
  answer: "1/6",
  given: "2/3",
  source: "PowerPrep",
  explain: "Subtract the first equation from the second: $y = -2$. Then $3x = 2 - y = 4$, so $x = \\tfrac{4}{3}$. Finally $x - 2z = 1$ gives $2z = x - 1 = \\tfrac{1}{3}$, so $z = \\tfrac{1}{6}$.",
  trap: "The last step is where $\\tfrac23$ comes from: with $2z = \\tfrac13$, dividing by 2 means multiplying by $\\tfrac12$ ($z = \\tfrac16$), but multiplying by 2 instead gives $\\tfrac23$. When an equation ends with a coefficient on the unknown, say the operation out loud &mdash; &ldquo;divide both sides by 2&rdquo; &mdash; before touching the fraction.",
  frac: true,
  fracLabel: "$z$" },
 {
  id: "three-eq-chain-1",
  topic: "Chained equations: solve, then substitute carefully",
  variant: 1,
  type: "ne",
  ts: 1787345000026,
  stem: "If $2x + y = 7$, $2x + 3y = 5$, and $y - 2w = 2$, what is the value of $w$?<br><span style=\"font-size:15px\">Give your answer as a fraction.</span>",
  answer: "-3/2",
  explain: "Subtract: $2y = -2$, so $y = -1$. Then $-2w = 2 - y = 3$, so $w = -\\tfrac{3}{2}$.",
  trap: "Negative fractions earn extra care in the divide step: $-2w = 3$ means $w = -\\tfrac32$, not $\\tfrac32$ or $-6$.",
  frac: true,
  fracLabel: "$w$" },
 {
  id: "remainder-translate-0",
  topic: "Remainders: translate, then list",
  variant: 0,
  type: "ma",
  ts: 1787345000027,
  stem: "When the positive integer $N$ is divided by 16, the remainder is 3. Which of the following integers could be the remainder when $N$ is divided by 6?<br><span style=\"font-size:15px\">Indicate <u>all</u> such integers.</span>",
  choices: ["$0$", "$1$", "$2$", "$3$", "$4$", "$5$"],
  answer: [1, 3, 5],
  source: "PowerPrep — reviewed together in session",
  explain: "Translate: $N = 16k + 3$. Now list: $k=0$: $3 \\to$ remainder $3$; $k=1$: $19 \\to 1$; $k=2$: $35 \\to 5$; $k=3$: $51 \\to 3$; $k=4$: $67 \\to 1$; $k=5$: $83 \\to 5$. The pattern cycles $3, 1, 5$, so the possible remainders are $1$, $3$, and $5$.",
  trap: "All the possibilities are odd &mdash; because $16k+3$ is always odd, and an odd number&rsquo;s remainder on division by 6 must be odd. That parity check kills half the choices instantly; the short list confirms all three odd ones occur." },
 {
  id: "remainder-translate-1",
  topic: "Remainders: translate, then list",
  variant: 1,
  type: "ma",
  ts: 1787345000028,
  stem: "When the positive integer $N$ is divided by 12, the remainder is 5. Which of the following integers could be the remainder when $N$ is divided by 8?<br><span style=\"font-size:15px\">Indicate <u>all</u> such integers.</span>",
  choices: ["$0$", "$1$", "$2$", "$3$", "$4$", "$5$"],
  answer: [1, 5],
  explain: "$N = 12k+5$: $5, 17, 29, 41, \\ldots$ give remainders $5, 1, 5, 1, \\ldots$ Only $1$ and $5$.",
  trap: "Translate to $N = 12k+5$, list until the cycle repeats. Odd $N$ rules out even remainders immediately." }
];
